daysUntilStale: 20
daysUntilClose: 7
exemptLabels:
  - ":bulb: feature request/idea"
  - ":bug: bug"
  - ":white_check_mark: PR accepted"
staleLabel: 💤 stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
